---
title: "Proect 1 Report"
author: "Yujung Chen, Ran Wei, Tuo Liu"
date: "`r Sys.Date()`"
output: pdf_document
---


### Introduction

#### Background and rationale
Cardiovascular disease (CVD) is a condition of heart and blood vessel disorders; it contains various types of diseases, mainly including coronary heart disease, stroke, peripheral arterial disease, and aortic disease. Moreover, 17.9 million people die of CVD each year according to WHO estimation. In the United States, one person dies every 34 seconds because of CVD. However, with such a high prevalence, the only prevention of CVD is to reduce the risk of possible etiological factors. There are many risk factors that have been identified in previous studies, and the risk factors have been closely related to human behavior such as smoking, diet, and physical activity.  Thus, it is important to assess the risk factors and manage them properly to reduce the possibility of developing CVD.\\

Behind those studies, Framingham Heart Study (FHS) plays a crucial role to provide the dataset for analysis. FHS is a prospective study started in 1984 by the US Public Health Service, aiming to understand the natural history of cardiovascular disease (CVD) and its possible causes. The population living in Framingham, Massachusetts was chosen to enroll in this study with nearly 15,000 participants across three generations. With the examinations that follow-up regularly every 6 years, the FHS provides a longitudinal dataset for identifying the potential biological and lifestyle risk factors. Giving more information on risk factors and their combined effect on CVD.


#### Objectives
To understand whether quitting smoking reduces the likelihood of incident cardiovascular disease (CVD), evaluate the importance of smoking as risk factors on CVD. We hypothesized that free living adults who quitted smoking would have a lower risk of incident cardiovascular disease than those who continued smoking.

### Study design
The FHS study is an non-randomized, observational, prospective, and longitudinal study. The participants in this study were recruited from people living in Framingham. The dataset used for building the model is a subset (n =4,434 participants; 2490 women, 1944 men; age 32-70 years) from the original cohort (5,209 participants) enrolled in 1948-50. Each participant has laboratory and questionnaire data from three examination periods separated by 6 year, with follow-up evaluation for a total of 24 years, collecting a total of 11,627 observations comprising 38 variables.

### Measures 
#### Outcome
- Primary outcome
The primary response of interest was CVD status among participants at multiple examination cycle from the Framingham Heart Study. 
- Secondary outcome

- Measurement & transformation
Main outcomes, CVD status,  was measured as a binary variable, encoded with 0 if no CVD disease condition was reported at each of three examination cycles and 1 if CVD condition was reported.


#### Exposure and covariates (LT)
- Main exposure
- Covariates
- Measurement & transformation


### Statistical methods
#### Model choice and rationale
The main response variable was binary as encoded 0/1, and the main predictor was binary with covariates being continuous and categorical variables,  which ascertained the eligibility of the application of logistic regression model on the data at hand. We only incorporated continued and never smokers from Examination 1 to 3 into our analyses assuming that longer exposure period would present better association with CVD, if any. 

#### Assumption check methods
Primarily, we used graphical approach, together with appropriate metrics,  to assess assumptions made for the logistic regression model. Relevant statistical tests were also employed here to test for certain characteristic of the model, i.e. goodness-of-fit.


#### Covariate adjustment
#### Alternative model (Ran)
#### Missing data
#### Sensitivity analysis 


### Results-text/table/fig (all)

Table 1 descriptive statistics
Table 2 covariates, model description
Table 3 covariate selection or alternative model 
Figure 1 bar chart
Figure 2 survival plot

### Discussion 


### Reference (Yurong)



### Appendix 1
Model assumption assessment

### Appendix 2
Show relevant statistical code